name: "Feature Request/Idea"
title: "[New Feature]: "
description: Suggest features, modifications, ideas and suggestions
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description of the feature, modification, idea or suggestion
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed implementation details (optional)
      placeholder: Suggest how to implement the feature.
    validations:
      required: false
